CREATE SCHEMA IF NOT EXISTS crypto;

GRANT ALL PRIVILEGES ON SCHEMA public TO admin;

CREATE TABLE wallets (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE cryptos (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE wallet_crypto (
    id SERIAL PRIMARY KEY,
    wallet_id INTEGER NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,
    crypto_id INTEGER NOT NULL REFERENCES cryptos(id) ON DELETE CASCADE,
    quantity DOUBLE PRECISION NOT NULL,
    price DOUBLE PRECISION NOT NULL
);